import { IFormField } from '../models/formField';
export const SERVICE_FIELDS: Array<IFormField> = [
  { field: 'id', label: 'Service ID', type: 'text', read: true },
  // { field: 'service_id', label: 'Service ID', type: 'text', read: true },
  {
    field: 'carrier_id',
    label: 'Client',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },
  {
    field: 'provider_location',
    label: 'Provider Location',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },
  {
    field: 'name',
    label: 'Customer',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },

  {
    field: 'street',
    label: 'Street',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },
  {
    field: 'city',
    label: 'City',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },
  {
    field: 'zip',
    label: 'Zip',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },

  {
    field: 'jobs',
    label: 'Jobs',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },

  {
    field: 'description',
    label: 'Description',
    type: 'text',
    required: true,
    create: true,
    filter: true,
    read: true,
  },
  {
    field: 'status',
    label: 'Status',
    type: 'text',
    filter: true,
    required: true,
    // create: true,
    read: true,
  },
];
